language: java
services:
  - docker
sudo: required
jdk:
  - openjdk12
cache:
  directories:
    - $HOME/.m2

script:
  - mvn clean package
  - docker build -t kitsdq/esda-aggregate .\edu.kit.ipd.are.esda.aggregate
  - docker build -t kitsdq/esda-analysis .\edu.kit.ipd.are.esda.analysis
  - docker build -t kitsdq/esda-importer .\edu.kit.ipd.are.esda.importer
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push kitsdq/esda-aggregate
  - docker push kitsdq/esda-analysis
  - docker push kitsdq/esda-importer